version: '3.8'

services:
  # Chatbot Service (LangGraph)
  chatbot:
    build:
      context: .
      dockerfile: services/chatbot/Dockerfile
    container_name: pharma-chatbot
    ports:
      - "8001:8001"
    environment:
      - CHATBOT_HOST=0.0.0.0
      - CHATBOT_PORT=8001
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
    volumes:
      - ./services/chatbot:/app/services/chatbot
      - ./shared:/app/shared
      - ./database:/app/database
      - ./models:/app/models
      - ./.env:/app/.env
    networks:
      - pharma-network
    restart: unless-stopped

  # Data API Service
  data-api:
    build:
      context: .
      dockerfile: services/data_api/Dockerfile
    container_name: pharma-data-api
    ports:
      - "8002:8002"
    environment:
      - DATA_API_HOST=0.0.0.0
      - DATA_API_PORT=8002
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
    volumes:
      - ./services/data_api:/app/services/data_api
      - ./shared:/app/shared
      - ./database:/app/database
      - ./models:/app/models
      - ./.env:/app/.env
    networks:
      - pharma-network
    restart: unless-stopped

  # Nginx Reverse Proxy (Optional)
  nginx:
    image: nginx:alpine
    container_name: pharma-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - chatbot
      - data-api
    networks:
      - pharma-network
    restart: unless-stopped

networks:
  pharma-network:
    driver: bridge

volumes:
  database:
  models: