# Multi-Agent System Configuration
# Version: 2.0.0 - Simplified for LangGraph 2025
# 단일 파일로 통합된 간소화 설정

system:
  version: "2.0.0"
  name: "Pharma AI Assistant"
  description: "제약회사 Multi-Agent 시스템"
  
# 에이전트 정의 (핵심만)
agents:
  analysis:
    name: "분석 에이전트"
    description: "실적 데이터 분석 및 통계 처리"
    keywords: ["분석", "실적", "매출", "통계", "추이", "비교", "달성률"]
    examples:
      - "지난 분기 매출 분석"
      - "거래처별 실적 비교"
      - "YoY 성장률 계산"
    capabilities:
      - text2sql
      - statistical_analysis
      - data_visualization
    confidence_threshold: 0.75
    
  search:
    name: "검색 에이전트"
    description: "정보 검색 및 데이터 조회"
    keywords: ["검색", "찾아", "조회", "확인", "정보", "자료", "어디"]
    examples:
      - "제품 최신 임상 데이터"
      - "경쟁사 신제품 정보"
      - "규정 변경사항 확인"
    capabilities:
      - internal_search
      - external_search
      - source_selection
    confidence_threshold: 0.65
    
  document:
    name: "문서 에이전트"
    description: "보고서 및 프레젠테이션 자동 생성"
    keywords: ["문서", "보고서", "작성", "생성", "만들어", "프레젠테이션"]
    examples:
      - "방문보고서 작성"
      - "제품설명회 자료 생성"
      - "월간 실적 보고서"
    capabilities:
      - report_generation
      - presentation_creation
      - template_management
    confidence_threshold: 0.8
    
  customer:
    name: "고객 에이전트"
    description: "고객 분석 및 맞춤 자료 추천"
    keywords: ["고객", "거래처", "병원", "의사", "맞춤", "추천", "성향"]
    examples:
      - "A병원 방문 자료 추천"
      - "심장내과 선호 자료"
      - "거래처 관심사 분석"
    capabilities:
      - customer_profiling
      - material_recommendation
      - preference_analysis
    confidence_threshold: 0.7

# 실행 전략
execution:
  routing:
    default_confidence: 0.6
    max_parallel_agents: 3
    timeout_ms: 30000
    
  patterns:
    sequential: ["search", "analysis", "document"]  # 순차 실행
    parallel: ["search", "customer"]  # 병렬 실행 가능
    supervisor: true  # Supervisor 패턴 활성화
    
  handoff:  # 에이전트 간 전환
    enabled: true
    protocol: "structured"
    required_fields: ["target", "payload", "reason"]

# 성능 최적화
optimization:
  cache:
    enabled: true
    ttl_seconds: 3600  # 1시간 (기존 5분에서 연장)
    max_size_mb: 100
    
  token_limits:
    prompt_max: 1000  # 50% 감축
    response_max: 2000  # 50% 감축
    
  batching:
    enabled: true
    size: 10
    timeout_ms: 5000

# LangGraph 통합
langgraph:
  state_management:
    type: "shared"  # 공유 상태
    schema:
      query: "string"
      intent: "string"
      agents: "array"
      results: "object"
      metadata: "object"
      
  checkpoints:  # Human-in-the-loop
    enabled: true
    points:
      - "before_document_generation"
      - "before_external_api_call"
      - "on_low_confidence"
      
  tracing:
    enabled: true
    level: "info"
    
# 에러 처리 (간소화)
error_handling:
  retry:
    max_attempts: 3
    backoff_ms: 1000
    
  fallback:
    use_cache: true
    default_agent: "search"
    
  circuit_breaker:
    enabled: true
    threshold: 5
    timeout_ms: 30000

# 모니터링 (핵심만)
monitoring:
  metrics:
    - response_time
    - success_rate
    - token_usage
    
  alerts:
    error_rate_threshold: 0.1
    latency_threshold_ms: 5000