# Customer Agent Configuration
# 고객/거래처 데이터 분석 및 맞춤 추천

agent:
  name: "customer_agent"
  display_name: "고객 데이터 분석 에이전트"
  version: "1.0.0"
  description: "고객 성향 분석 및 맞춤형 자료 추천"
  icon: "👥"
  color: "#9C27B0"

# 에이전트 능력 정의
capabilities:
  customer_profiling:
    confidence: 0.91
    description: "고객/거래처 프로파일링"
    analysis_dimensions:
      - prescribing_patterns
      - preference_history
      - interaction_frequency
      - response_rates
      - specialty_focus
      - decision_factors
      
  preference_analysis:
    confidence: 0.88
    description: "선호도 패턴 분석"
    methods:
      - historical_analysis
      - behavioral_clustering
      - preference_prediction
      - trend_identification
      
  material_recommendation:
    confidence: 0.86
    description: "맞춤형 자료 추천"
    recommendation_types:
      - clinical_studies
      - product_materials
      - presentation_styles
      - communication_channels
      - meeting_formats
      
  engagement_scoring:
    confidence: 0.89
    description: "고객 참여도 평가"
    metrics:
      - visit_frequency
      - response_quality
      - product_adoption
      - feedback_sentiment
      - relationship_strength

# 고객 세그먼트 정의
customer_segments:
  by_specialty:
    internal_medicine:
      key_interests: ["efficacy", "safety", "guidelines"]
      preferred_format: ["clinical_data", "case_studies"]
      
    cardiology:
      key_interests: ["cardiovascular_outcomes", "risk_factors"]
      preferred_format: ["landmark_trials", "meta_analysis"]
      
    endocrinology:
      key_interests: ["metabolic_effects", "long_term_data"]
      preferred_format: ["real_world_evidence", "patient_profiles"]
      
  by_adoption_stage:
    early_adopter:
      characteristics: ["innovation_seeking", "opinion_leader"]
      approach: ["cutting_edge_data", "exclusive_previews"]
      
    mainstream:
      characteristics: ["evidence_based", "peer_influenced"]
      approach: ["established_data", "peer_testimonials"]
      
    conservative:
      characteristics: ["risk_averse", "guideline_follower"]
      approach: ["safety_data", "regulatory_approvals"]
      
  by_institution_type:
    university_hospital:
      focus: ["research", "education", "innovation"]
      materials: ["detailed_studies", "mechanism_focused"]
      
    general_hospital:
      focus: ["practical_application", "efficiency"]
      materials: ["practical_guides", "cost_effectiveness"]
      
    clinic:
      focus: ["patient_convenience", "simplicity"]
      materials: ["patient_materials", "quick_references"]

# 트리거 조건
triggers:
  keywords:
    high_priority:
      - "고객"
      - "거래처"
      - "의사"
      - "병원"
      - "성향"
      - "선호"
      - "맞춤"
      
    medium_priority:
      - "특성"
      - "패턴"
      - "추천"
      - "관심사"
      - "니즈"
      
    contextual:
      - "어떤 자료"
      - "뭘 가져가야"
      - "관심있어할"
      - "좋아하는"
      - "선호하는"
      - "효과적인"
      
  patterns:
    - pattern: ".*고객.*분석.*"
      confidence_boost: 0.3
      priority: "high"
      
    - pattern: ".*거래처.*성향.*"
      confidence_boost: 0.3
      priority: "high"
      
    - pattern: ".*맞춤.*자료.*"
      confidence_boost: 0.25
      priority: "medium"
      
    - pattern: ".*추천.*자료.*"
      confidence_boost: 0.25
      priority: "medium"

# 분석 차원
analysis_dimensions:
  professional:
    specialty:
      weight: 0.25
      factors: ["board_certification", "sub_specialty", "research_focus"]
      
    experience:
      weight: 0.15
      factors: ["years_practicing", "institution_history", "leadership_roles"]
      
    influence:
      weight: 0.20
      factors: ["opinion_leader", "speaker_activity", "publication_record"]
      
  behavioral:
    prescribing:
      weight: 0.30
      factors: ["product_usage", "switching_patterns", "dosing_preferences"]
      
    engagement:
      weight: 0.25
      factors: ["meeting_attendance", "question_frequency", "feedback_quality"]
      
    communication:
      weight: 0.15
      factors: ["preferred_channels", "response_times", "interaction_style"]
      
  institutional:
    hospital_type:
      weight: 0.20
      factors: ["size", "specialization", "patient_volume"]
      
    formulary:
      weight: 0.25
      factors: ["listing_status", "restrictions", "competition"]
      
    decision_process:
      weight: 0.15
      factors: ["committee_structure", "approval_timeline", "key_stakeholders"]

# 추천 엔진
recommendation_engine:
  data_sources:
    - crm_history
    - visit_reports  
    - email_interactions
    - event_attendance
    - product_adoption
    
  algorithms:
    collaborative_filtering:
      description: "비슷한 프로필의 고객 선호도 기반"
      weight: 0.3
      
    content_based:
      description: "과거 관심사 기반"
      weight: 0.4
      
    hybrid:
      description: "복합 알고리즘"
      weight: 0.3
      
  output_format:
    recommendations:
      - material_type
      - relevance_score
      - reasoning
      - timing_suggestion
      - delivery_method

# 사용 예시
examples:
  - query: "A병원 김박사님 방문할 때 어떤 자료를 가져가야 할까?"
    analysis_type: "individual_preference"
    data_points: ["past_visits", "specialty", "recent_interests"]
    expected_output: "맞춤 자료 추천 리스트"
    
  - query: "심장내과 전문의들이 관심있어할 만한 자료는?"
    analysis_type: "segment_analysis"
    segment: "cardiology"
    expected_output: "전문과별 선호 자료"
    
  - query: "B거래처의 최근 관심사 변화 분석"
    analysis_type: "trend_analysis"
    timeframe: "last_6_months"
    expected_output: "관심사 변화 트렌드"
    
  - query: "신규 거래처 C병원 접근 전략"
    analysis_type: "new_customer_strategy"
    data_points: ["institution_profile", "peer_hospitals", "market_position"]
    expected_output: "접근 전략 및 자료 추천"

# 실행 설정
execution:
  timeout: 25
  max_retries: 2
  cache_ttl: 3600  # 1 hour
  
  analysis_depth:
    quick: 5  # seconds
    standard: 15
    deep: 30
    
  data_freshness:
    real_time: ["current_formulary", "recent_visits"]
    daily: ["prescribing_data", "email_interactions"]
    weekly: ["market_trends", "competitive_intelligence"]

# 성향 분석 모델
preference_models:
  learning_style:
    visual:
      indicators: ["requests_slides", "prefers_charts", "asks_for_diagrams"]
      recommendations: ["infographics", "animated_presentations", "visual_aids"]
      
    analytical:
      indicators: ["asks_detailed_questions", "requests_raw_data", "compares_studies"]
      recommendations: ["detailed_studies", "statistical_analyses", "comparative_data"]
      
    practical:
      indicators: ["focuses_on_application", "asks_about_real_world", "patient_scenarios"]
      recommendations: ["case_studies", "practical_guides", "patient_materials"]
      
  decision_factors:
    evidence_driven:
      weight: 0.35
      materials: ["clinical_trials", "guidelines", "meta_analyses"]
      
    patient_focused:
      weight: 0.30
      materials: ["patient_outcomes", "quality_of_life", "adherence_data"]
      
    cost_conscious:
      weight: 0.20
      materials: ["pharmacoeconomics", "budget_impact", "cost_effectiveness"]
      
    innovation_oriented:
      weight: 0.15
      materials: ["mechanism_of_action", "novel_features", "pipeline_data"]

# 자료 매칭 로직
material_matching:
  scoring_factors:
    relevance:
      weight: 0.35
      calculation: "keyword_match + topic_similarity"
      
    recency:
      weight: 0.20
      calculation: "publication_date + update_frequency"
      
    preference_fit:
      weight: 0.25
      calculation: "historical_engagement + peer_preference"
      
    timing:
      weight: 0.20
      calculation: "seasonality + product_lifecycle + visit_frequency"
      
  threshold:
    minimum_score: 0.7
    recommended_count: 5
    maximum_count: 10

# 프롬프트 템플릿
prompts:
  system: |
    당신은 제약회사의 고객 인사이트 전문가입니다.
    고객과 거래처의 특성을 분석하여 최적의 맞춤형 접근 전략을 수립합니다.
    
    핵심 역할:
    1. 고객/거래처 프로파일 분석
    2. 선호도 및 관심사 파악
    3. 맞춤형 자료 및 접근법 추천
    4. 관계 강화 전략 수립
    
    준수 사항:
    - 개인정보 보호 및 윤리적 분석
    - 데이터 기반 객관적 추천
    - 고객 가치 중심 접근
    - 장기적 관계 구축 초점
    
  analysis_template: |
    ## 고객 분석: {customer_name}
    
    ### 기본 프로필
    - 전문과: {specialty}
    - 소속: {institution}
    - 경력: {experience}
    
    ### 선호도 분석
    - 학습 스타일: {learning_style}
    - 의사결정 요인: {decision_factors}
    - 커뮤니케이션 선호: {communication_preference}
    
    ### 최근 활동
    {recent_activities}
    
    ### 추천 자료
    {recommended_materials}
    
    ### 접근 전략
    {approach_strategy}
    
  recommendation_template: |
    ## 맞춤 자료 추천
    
    대상: {target_customer}
    목적: {visit_purpose}
    
    ### 핵심 추천 자료 (우선순위)
    1. {material_1} - {reason_1}
    2. {material_2} - {reason_2}
    3. {material_3} - {reason_3}
    
    ### 보조 자료
    - {supplementary_materials}
    
    ### 전달 방법
    {delivery_recommendation}
    
    ### 후속 조치
    {follow_up_plan}

# 출력 형식
output_formats:
  customer_profile:
    sections:
      - basic_info
      - preference_summary
      - engagement_history
      - recommendation_list
      
  segment_analysis:
    sections:
      - segment_characteristics
      - common_preferences
      - effective_approaches
      - material_suggestions
      
  strategy_report:
    sections:
      - customer_insights
      - opportunity_analysis
      - recommended_actions
      - success_metrics

# 성능 메트릭
performance_metrics:
  accuracy:
    preference_prediction: 0.85
    material_relevance: 0.88
    engagement_forecast: 0.80
    
  effectiveness:
    adoption_rate: 0.75
    satisfaction_score: 4.3
    relationship_improvement: 0.30
    
  efficiency:
    analysis_speed: 10  # seconds
    recommendation_time: 5
    update_frequency: "daily"

# 개인정보 보호
privacy:
  data_handling:
    anonymization: true
    encryption: true
    access_control: "strict"
    
  compliance:
    - "Personal Information Protection Act"
    - "GDPR where applicable"
    - "Company Privacy Policy"
    
  retention:
    active_customers: "ongoing"
    inactive_customers: "2_years"
    aggregated_data: "5_years"

# 학습 및 개선
learning:
  feedback_loop:
    collect_outcomes: true
    track_effectiveness: true
    adjust_models: true
    
  pattern_recognition:
    identify_trends: true
    segment_evolution: true
    preference_shifts: true
    
  optimization:
    algorithm_tuning: "monthly"
    weight_adjustment: "quarterly"
    model_retraining: "semi_annual"
