# Document Agent Configuration  
# 문서 자동 생성 - 방문보고서, 제품설명회 자료 등

agent:
  name: "document_agent"
  display_name: "문서 자동생성 에이전트"
  version: "1.0.0"
  description: "각종 보고서 및 프레젠테이션 자료 자동 생성"
  icon: "📄"
  color: "#FF6B6B"

# 에이전트 능력 정의
capabilities:
  document_generation:
    confidence: 0.93
    description: "다양한 형식의 문서 자동 생성"
    document_types:
      - official_visit_report
      - unofficial_visit_report
      - product_presentation
      - presentation_result_report
      - market_analysis_report
      - competitive_analysis
      - clinical_summary
      
  template_management:
    confidence: 0.90
    description: "문서 템플릿 선택 및 적용"
    features:
      - dynamic_template_selection
      - custom_styling
      - brand_compliance
      - multi_format_export
      
  content_synthesis:
    confidence: 0.88
    description: "여러 소스의 정보 종합"
    methods:
      - information_aggregation
      - key_point_extraction
      - narrative_generation
      - visual_integration
      
  compliance_check:
    confidence: 0.95
    description: "규정 준수 및 검증"
    checks:
      - regulatory_compliance
      - brand_guidelines
      - legal_review
      - data_accuracy

# 문서 유형별 정의
document_types:
  official_visit_report:
    name: "공식 방문보고서"
    description: "공식적인 병원/거래처 방문 보고서"
    required_sections:
      - header:
          - report_date
          - visit_date
          - hospital_name
          - department
          - attendees
      - body:
          - visit_purpose
          - discussion_topics
          - product_presentation
          - customer_feedback
          - competitive_info
      - conclusion:
          - action_items
          - follow_up_plan
          - next_visit_schedule
    compliance_level: "high"
    approval_required: true
    retention_period: "5_years"
    
  unofficial_visit_report:
    name: "비공식 방문보고서"
    description: "내부 참고용 간략 방문 기록"
    required_sections:
      - summary:
          - date
          - location
          - key_contacts
      - notes:
          - main_discussions
          - observations
          - insights
      - action_points:
          - immediate_actions
          - future_considerations
    compliance_level: "medium"
    approval_required: false
    retention_period: "2_years"
    
  product_presentation:
    name: "제품설명회 자료"
    description: "의료진 대상 제품 프레젠테이션"
    required_sections:
      - opening:
          - title_slide
          - agenda
          - company_introduction
      - product_overview:
          - indication
          - mechanism_of_action
          - clinical_benefits
      - clinical_evidence:
          - study_design
          - efficacy_data
          - safety_profile
      - practical_information:
          - dosing_administration
          - patient_selection
          - monitoring
      - closing:
          - key_takeaways
          - q_and_a
          - contact_information
    compliance_level: "high"
    approval_required: true
    visual_elements: "required"
    
  presentation_result_report:
    name: "제품설명회 결과보고서"
    description: "제품설명회 실시 후 결과 정리"
    required_sections:
      - event_summary:
          - date_time
          - venue
          - presenter
          - audience_count
          - audience_profile
      - presentation_content:
          - topics_covered
          - materials_used
          - duration
      - audience_response:
          - questions_asked
          - feedback_received
          - interest_level
      - outcomes:
          - follow_up_requests
          - prescribing_intent
          - additional_info_needed
      - next_steps:
          - action_items
          - follow_up_timeline
    compliance_level: "medium"
    approval_required: false

# 트리거 조건
triggers:
  keywords:
    high_priority:
      - "문서"
      - "보고서"
      - "작성"
      - "만들어"
      - "생성"
      - "프레젠테이션"
      - "발표자료"
      
    medium_priority:
      - "정리"
      - "요약"
      - "기록"
      - "문서화"
      - "자료"
      
    contextual:
      - "방문보고서"
      - "설명회"
      - "공식문서"
      - "회의록"
      - "제안서"
      
  patterns:
    - pattern: ".*방문.*보고서.*"
      confidence_boost: 0.3
      document_type: "visit_report"
      
    - pattern: ".*제품.*설명.*"
      confidence_boost: 0.3
      document_type: "product_presentation"
      
    - pattern: ".*결과.*정리.*"
      confidence_boost: 0.25
      document_type: "result_report"

# 템플릿 관리
templates:
  selection_criteria:
    - document_type
    - audience_type
    - formality_level
    - compliance_requirements
    - brand_guidelines
    
  customization_options:
    - color_scheme
    - font_selection
    - logo_placement
    - header_footer
    - section_ordering
    
  version_control:
    enabled: true
    auto_update: true
    rollback_capability: true

# 사용 예시
examples:
  - query: "어제 A병원 방문한 내용으로 공식 보고서 작성해줘"
    document_type: "official_visit_report"
    data_sources: ["visit_notes", "crm_data", "product_info"]
    expected_output: "완성된 공식 방문보고서"
    
  - query: "B약품 제품설명회 프레젠테이션 자료 만들어줘"
    document_type: "product_presentation"
    data_sources: ["product_database", "clinical_studies", "marketing_materials"]
    expected_output: "프레젠테이션 슬라이드"
    
  - query: "오늘 실시한 설명회 결과 보고서 작성"
    document_type: "presentation_result_report"
    data_sources: ["event_data", "attendance_record", "feedback_forms"]
    expected_output: "결과보고서 문서"
    
  - query: "지난주 거래처 방문 내용 간단히 정리"
    document_type: "unofficial_visit_report"
    data_sources: ["calendar_events", "email_correspondence", "notes"]
    expected_output: "비공식 방문 요약"

# 실행 설정
execution:
  timeout: 45
  max_retries: 2
  auto_save: true
  save_interval: 60  # seconds
  
  generation_steps:
    1: "data_collection"
    2: "template_selection"
    3: "content_generation"
    4: "formatting"
    5: "compliance_check"
    6: "finalization"
    
  quality_checks:
    - completeness
    - accuracy
    - consistency
    - compliance
    - readability

# 콘텐츠 생성 전략
content_generation:
  strategies:
    structured:
      description: "템플릿 기반 구조화된 생성"
      use_for: ["official_documents", "compliance_required"]
      
    narrative:
      description: "스토리텔링 방식 생성"
      use_for: ["presentations", "executive_summaries"]
      
    data_driven:
      description: "데이터 중심 생성"
      use_for: ["analytical_reports", "performance_reviews"]
      
  tone_adjustment:
    formal:
      - official_reports
      - regulatory_submissions
    professional:
      - client_presentations
      - internal_reports
    informal:
      - team_updates
      - quick_summaries

# 출력 형식
output_formats:
  supported:
    - pdf:
        features: ["print_ready", "digital_signature", "watermark"]
    - docx:
        features: ["editable", "track_changes", "comments"]
    - pptx:
        features: ["animations", "speaker_notes", "handouts"]
    - html:
        features: ["responsive", "interactive", "embedded_media"]
    - markdown:
        features: ["version_control", "lightweight", "convertible"]
        
  default_by_type:
    official_visit_report: "pdf"
    unofficial_visit_report: "docx"
    product_presentation: "pptx"
    presentation_result_report: "pdf"

# 프롬프트 템플릿
prompts:
  system: |
    당신은 제약회사의 전문 문서 작성 전문가입니다.
    다양한 유형의 보고서와 프레젠테이션을 작성하며, 규정 준수와 품질을 보장합니다.
    
    핵심 역할:
    1. 사용자 요구사항에 맞는 문서 유형 파악
    2. 필요한 정보 수집 및 구조화
    3. 템플릿 적용 및 콘텐츠 생성
    4. 규정 준수 및 품질 검증
    
    준수 사항:
    - 정확성: 모든 정보의 정확성 확인
    - 완전성: 필수 섹션 누락 없음
    - 일관성: 브랜드 가이드라인 준수
    - 규정 준수: 관련 규정 및 가이드라인 준수
    
  document_generation: |
    ## 문서 생성 요청
    문서 유형: {document_type}
    목적: {purpose}
    대상 독자: {audience}
    
    ## 수집된 정보
    {collected_data}
    
    ## 생성 지침
    - 톤: {tone}
    - 길이: {length}
    - 특별 요구사항: {special_requirements}
    
  quality_review: |
    ## 품질 검토 체크리스트
    ☐ 모든 필수 섹션 포함
    ☐ 정보 정확성 확인
    ☐ 브랜드 가이드라인 준수
    ☐ 규정 요구사항 충족
    ☐ 문법 및 맞춤법 검사
    ☐ 시각 자료 적절성
    ☐ 참고문헌 정확성

# 시각 요소 관리
visual_elements:
  charts:
    types: ["bar", "line", "pie", "scatter", "heatmap"]
    auto_generate: true
    data_source: "analysis_agent"
    
  images:
    sources: ["product_library", "approved_gallery", "generated"]
    compliance_check: true
    
  tables:
    auto_format: true
    responsive: true
    sortable: true
    
  infographics:
    templates: ["process_flow", "comparison", "timeline", "statistics"]
    customizable: true

# 협업 기능
collaboration:
  review_workflow:
    enabled: true
    stages:
      - draft
      - internal_review
      - compliance_review
      - final_approval
      
  commenting:
    enabled: true
    track_changes: true
    version_history: true
    
  sharing:
    internal: true
    external: "with_approval"
    expiration: "configurable"

# 성능 메트릭
performance_metrics:
  quality:
    accuracy_score: 0.95
    completeness_score: 0.98
    compliance_rate: 1.0
    
  efficiency:
    avg_generation_time: 30  # seconds
    revision_cycles: 1.5
    approval_time: 24  # hours
    
  user_satisfaction:
    rating_threshold: 4.5
    adoption_rate: 0.85
    reuse_rate: 0.7

# 보안 및 규정 준수
security:
  data_handling:
    encryption: "AES-256"
    access_control: "role_based"
    audit_trail: true
    
  compliance:
    regulations:
      - "KFDA"
      - "Fair Trade"
      - "Privacy Act"
    validation:
      - pre_generation
      - post_generation
      
  retention:
    official_documents: "5_years"
    draft_documents: "1_year"
    templates: "permanent"

# 학습 및 개선
learning:
  template_optimization:
    track_usage: true
    collect_feedback: true
    auto_improve: true
    
  content_improvement:
    analyze_edits: true
    learn_preferences: true
    suggest_improvements: true
    
  performance_tracking:
    generation_success_rate: true
    approval_rate: true
    revision_frequency: true
