# Search Agent Configuration
# 정보 검색, 데이터 입력, 문서 생성 필요성 판단

agent:
  name: "search_agent"
  display_name: "정보 검색 및 데이터 입력 에이전트"
  version: "1.0.0"
  description: "내외부 정보 검색, 데이터 입력 판단, 문서 생성 라우팅"
  icon: "🔍"
  color: "#00BFA5"

# 에이전트 능력 정의
capabilities:
  information_retrieval:
    confidence: 0.92
    description: "다양한 소스에서 정보 검색"
    sources:
      internal:
        - knowledge_base
        - document_repository
        - product_database
        - regulation_database
        - clinical_data
      external:
        - web_search
        - news_api
        - medical_journals
        - regulatory_updates
        - competitor_analysis
      
  source_selection:
    confidence: 0.88
    description: "최적의 정보 소스 선택"
    strategies:
      - relevance_based
      - freshness_priority
      - authority_ranking
      - cost_optimization
      
  data_entry_detection:
    confidence: 0.85
    description: "데이터 입력 필요성 판단"
    entry_types:
      - visit_report_entry
      - customer_update
      - product_feedback
      - adverse_event
      - sales_activity
      
  document_need_assessment:
    confidence: 0.87
    description: "문서 생성 필요성 평가"
    assessment_criteria:
      - query_intent
      - data_complexity
      - audience_type
      - compliance_requirement

# 트리거 조건
triggers:
  keywords:
    high_priority:
      - "검색"
      - "찾아"
      - "조회"
      - "확인"
      - "알려줘"
      - "정보"
      - "자료"
      - "입력"
      
    medium_priority:
      - "어디"
      - "언제"
      - "누가"
      - "뭐"
      - "어떻게"
      - "업데이트"
      - "등록"
      
    contextual:
      - "최신"
      - "규정"
      - "가이드라인"
      - "경쟁사"
      - "시장동향"
      - "뉴스"
      - "학회"
      - "임상"
      
  patterns:
    - pattern: ".*제품.*정보.*"
      confidence_boost: 0.25
      priority: "high"
      
    - pattern: ".*규정.*확인.*"
      confidence_boost: 0.3
      priority: "high"
      
    - pattern: ".*경쟁.*동향.*"
      confidence_boost: 0.25
      priority: "medium"
      
    - pattern: ".*방문.*입력.*"
      confidence_boost: 0.3
      priority: "high"
      action: "data_entry"
      
    - pattern: ".*보고서.*필요.*"
      confidence_boost: 0.2
      priority: "medium"
      action: "document_routing"

# 정보 소스 우선순위
source_priority:
  product_info:
    1: "product_database"
    2: "knowledge_base"
    3: "clinical_data"
    
  regulation:
    1: "regulation_database"
    2: "regulatory_updates"
    3: "web_search"
    
  market_info:
    1: "competitor_analysis"
    2: "news_api"
    3: "web_search"
    
  customer_info:
    1: "crm_system"
    2: "visit_reports"
    3: "document_repository"

# 라우팅 규칙
routing_rules:
  to_document_agent:
    conditions:
      - "complex_data_presentation"
      - "formal_report_needed"
      - "multiple_stakeholders"
      - "compliance_required"
    triggers:
      - "보고서 작성"
      - "문서로 만들어"
      - "발표자료"
      - "공식 문서"
      
  to_analysis_agent:
    conditions:
      - "numerical_analysis_needed"
      - "statistical_processing"
      - "trend_identification"
    triggers:
      - "분석 필요"
      - "통계 처리"
      - "수치 확인"
      
  to_customer_agent:
    conditions:
      - "customer_specific"
      - "personalization_needed"
    triggers:
      - "고객 맞춤"
      - "거래처 특성"

# 사용 예시
examples:
  - query: "A제품의 최신 임상 데이터를 찾아줘"
    intent: "product_clinical_search"
    source_selection: ["clinical_data", "medical_journals"]
    document_need: false
    expected_output: "임상 데이터 요약"
    
  - query: "경쟁사 B의 신제품 출시 정보 검색"
    intent: "competitor_product_search"
    source_selection: ["competitor_analysis", "news_api"]
    document_need: true
    route_to: "document_agent"
    expected_output: "경쟁사 분석 보고서"
    
  - query: "오늘 방문한 C병원 방문 내용 입력해야 해"
    intent: "visit_report_entry"
    action: "data_entry"
    form_type: "visit_report"
    expected_output: "방문보고서 입력 폼"
    
  - query: "새로운 보험 급여 규정 확인"
    intent: "regulation_search"
    source_selection: ["regulation_database", "regulatory_updates"]
    document_need: true
    expected_output: "규정 변경사항 문서"

# 실행 설정
execution:
  timeout: 20
  max_retries: 3
  parallel_search: true
  max_parallel_sources: 5
  cache_ttl: 1800  # 30 minutes
  
  search_limits:
    internal: 100
    external: 50
    news: 20
    
  freshness_requirements:
    regulation: 1  # days
    news: 7
    product_info: 30
    general: 90

# 검색 전략
search_strategies:
  comprehensive:
    description: "모든 관련 소스 검색"
    sources: "all"
    depth: "deep"
    use_when:
      - "critical_decision"
      - "compliance_check"
      - "comprehensive_report"
      
  quick:
    description: "빠른 기본 검색"
    sources: "primary"
    depth: "shallow"
    use_when:
      - "simple_query"
      - "known_location"
      - "time_sensitive"
      
  targeted:
    description: "특정 소스 집중 검색"
    sources: "selected"
    depth: "medium"
    use_when:
      - "specific_request"
      - "expert_query"

# 데이터 입력 폼
data_entry_forms:
  visit_report:
    fields:
      - hospital_name: "required"
      - visit_date: "required"
      - attendees: "required"
      - purpose: "required"
      - products_discussed: "optional"
      - next_steps: "optional"
      - attachments: "optional"
      
  customer_update:
    fields:
      - customer_id: "required"
      - update_type: "required"
      - details: "required"
      - effective_date: "required"
      
  product_feedback:
    fields:
      - product_name: "required"
      - feedback_type: "required"
      - source: "required"
      - details: "required"
      - severity: "optional"

# 프롬프트 템플릿
prompts:
  system: |
    당신은 제약회사의 정보 검색 및 데이터 관리 전문가입니다.
    사용자의 질의를 분석하여 최적의 정보 소스를 선택하고 필요한 정보를 제공합니다.
    
    핵심 역할:
    1. 질의 의도 파악 및 정보 소스 결정
    2. 내외부 정보 효율적 검색
    3. 데이터 입력 필요성 판단
    4. 문서 생성 필요시 적절한 에이전트로 라우팅
    
    준수 사항:
    - 정확성: 신뢰할 수 있는 소스 우선
    - 최신성: 가장 최근 정보 제공
    - 완전성: 필요한 모든 정보 수집
    - 효율성: 최적의 검색 경로 선택
    
  search_template: |
    ## 검색 요청: {query}
    
    ### 검색 전략
    - 선택된 소스: {selected_sources}
    - 검색 깊이: {search_depth}
    - 우선순위: {priority}
    
    ### 검색 결과
    {search_results}
    
    ### 추가 작업 필요
    - 문서 생성: {document_needed}
    - 데이터 입력: {data_entry_needed}
    - 추가 분석: {analysis_needed}
    
  routing_decision: |
    질의 분석 결과:
    - 의도: {intent}
    - 복잡도: {complexity}
    - 필요 작업: {required_actions}
    
    라우팅 결정:
    - 대상 에이전트: {target_agent}
    - 이유: {routing_reason}
    - 전달 데이터: {forwarded_data}

# 출력 형식
output_formats:
  search_results:
    structure:
      - source_info
      - relevance_score
      - content_summary
      - full_content_link
      - metadata
      
  data_entry_response:
    structure:
      - form_type
      - required_fields
      - validation_rules
      - submission_endpoint
      
  routing_response:
    structure:
      - target_agent
      - forwarded_query
      - context_data
      - expected_outcome

# 성능 메트릭
performance_metrics:
  search_quality:
    relevance_threshold: 0.8
    completeness_target: 0.9
    freshness_score: 0.85
    
  efficiency:
    avg_search_time: 3000  # ms
    cache_hit_rate: 0.6
    parallel_efficiency: 0.8
    
  routing_accuracy:
    correct_routing: 0.95
    document_need_detection: 0.9
    entry_need_detection: 0.88

# 보안 및 규정 준수
security:
  data_classification:
    public: "no_restriction"
    internal: "employee_only"
    confidential: "need_to_know"
    restricted: "special_permission"
    
  compliance_checks:
    - personal_info_masking
    - audit_trail
    - access_control
    - retention_policy

# 학습 및 개선
learning:
  search_optimization:
    track_patterns: true
    improve_ranking: true
    update_frequency: "daily"
    
  routing_improvement:
    collect_feedback: true
    analyze_patterns: true
    auto_adjust: true
    
  source_evaluation:
    reliability_scoring: true
    freshness_tracking: true
    usage_analytics: true
